### ISSUE TITLE
Issue with helm-deft-build-cmd

### ISSUE THREAD

**Issue by zxcvbn97** [dfeich/helm-deft#1]
Hi dfeich, 

Thank you for the amazing helm-deft extension. I found it speed amazing.

One issue I am having is that it can not match content of the files. Possiblly because of the grep command or because of the zsh shell I'm using. Please see attached image. 

![image](https://cloud.githubusercontent.com/assets/9757976/7195767/073348a4-e48b-11e4-9de2-9f7f8842cf3e.png)

**Comment by dfeich** [comment]
Hi zxcvbn97

This is actually an unfinished product and it has a number of flaws. I use
it all the time for finding my org mode notes files, since I am doing
everything in org mode, really - from meeting notes to documents to
intensive usage of org babel functionality for executable documents and
even for the remote installation of servers.

I wanted to have something similar to deft, but able to deal with multiple
directories or hierarchies of directories. What you found was a first try
with helm, but it has some essential flaws, and I continually tell myself
to improve it... I just need some free evening. E.g. one problem currently
is that I want to use the same asynchronous process to produce two helm
sources from. And this seems to be a limitation in helm. It cannot deal
nicely with it, and I sometimes need to type spaces in order to have all
the sources updated. But it works more or less.
One other essential problem, and this is the one you stumbled upon, is that
the finding of the files is done by shell *grep"... so it has some issues
if you enter characters that the shell has issues with. The helm matching
afterwards is done by helm itself. So, a slight mismatch. As I said, I need
to improve it a lot, and this was just a first draft for getting it done. I
did not publish it in MELPA due to these shortcomings. For myself, it
already is so useful that it is my main method for locating and jumping to
the org file I am looking for.

Sorry for the current bugs.

Cheers,
Derek

**Comment by dfeich** [comment]
Closing. Old.
